repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3
        files: ^config/

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: [--profile=black]
        files: ^config/

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

-   repo: local
    hooks:
    -   id: django-tests
        name: Tests Django (gestionBatiment)
        entry: python config/manage.py test gestionBatiment.tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
