"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from datetime import timedelta  # AJOUT pour la configuration JWT
from pathlib import Path

from decouple import config

RUNNING_TESTS = "test" in sys.argv or "pytest" in sys.modules

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# CORRECTION DÉPLOIEMENT : piloté par variable d'env, False par défaut (sécurité par défaut)
DEBUG = config("DEBUG", default=False, cast=bool)

# CORRECTION DÉPLOIEMENT : accepte les hôtes Render en plus du localhost de dev
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Librairies tierces
    "corsheaders",
    "rest_framework",  # CORRECTION : Placé AVANT son extension SimpleJWT
    "rest_framework_simplejwt",
    "django_filters",
    # "django_celery_beat",
    "phonenumbers",
    # Applications locales
    "gestionBatiment",
]


#==================== STOCKAGE MÉDIA (Supabase Storage, S3-compatible) ====================

INSTALLED_APPS += ["storages"]

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_ACCESS_KEY_ID = config("SUPABASE_S3_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("SUPABASE_S3_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("SUPABASE_S3_BUCKET_NAME", default="media")
AWS_S3_ENDPOINT_URL = config(
    "SUPABASE_S3_ENDPOINT_URL"
)  # https://<project-ref>.supabase.co/storage/v1/s3
AWS_S3_REGION_NAME = config("SUPABASE_S3_REGION", default="eu-central-1")

# Supabase exige le "path-style" (bucket dans le chemin, pas en sous-domaine)
AWS_S3_ADDRESSING_STYLE = "path"
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False

#CORRECTION : sert les fichiers via l'API publique Supabase (plus rapide, sans
#passer par le protocole S3 pour chaque lecture) plutôt que via l'endpoint S3
AWS_S3_CUSTOM_DOMAIN = (
    f"{config('SUPABASE_PROJECT_REF')}.supabase.co/storage/v1/object/public/"
    f"{AWS_STORAGE_BUCKET_NAME}"
)


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Parfaitement positionné en haut
    "django.middleware.security.SecurityMiddleware",
    # AJOUT DÉPLOIEMENT : WhiteNoise juste après SecurityMiddleware pour servir
    # les fichiers statiques (admin Django, DRF browsable API) sans serveur dédié
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432", cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# AJOUT DÉPLOIEMENT : dossier où collectstatic rassemble tous les fichiers
# statiques avant que WhiteNoise les serve en prod
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
# CLOUDINARY_STORAGE = {
#     "CLOUD_NAME": config("CLOUDINARY_CLOUD_NAME"),
#     "API_KEY": config("CLOUDINARY_API_KEY"),
#     "API_SECRET": config("CLOUDINARY_API_SECRET"),
# }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuration email gratuite (SMTP Gmail exemple)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ==================== CONFIGURATION CORS (FRONTEND CONNECT) ====================

# CORRECTION DÉPLOIEMENT : origines pilotées par variable d'env pour inclure
# le domaine Render du frontend en prod, tout en gardant localhost en dev
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:4200,http://127.0.0.1:4200"
).split(",")

# CORRECTION SÉCURITÉ : Autoriser explicitement l'en-tête d'authentification et de contenu
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",  # INDISPENSABLE pour que le frontend envoie le token JWT
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_USE_TLS = config("EMAIL_USE_TLS")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
# CELERY_TIMEZONE = TIME_ZONE
# CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Pour exécuter les tâches Celery de façon synchrone pendant les tests
if RUNNING_TESTS:
    # CELERY_TASK_ALWAYS_EAGER = True
    # CELERY_TASK_EAGER_PROPAGATES = True
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
