# Generated by Django 6.0.5 on 2026-07-06 12:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBureau',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=50)),
                ('nombre_etages', models.IntegerField(default=0)),
                ('date_construction', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietaire_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietaire_telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CM')),
                ('proprietaire_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('proprietaire_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietaire_type_piece', models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('AUTRE', 'Autre')], max_length=20, null=True)),
                ('proprietaire_numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('unite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('espace', models.FloatField(default=0.0)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé')], default='DISPONIBLE', max_length=20)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bureaux', to='gestionBatiment.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRAVAILLEUR', 'Travailleur'), ('MANAGER', 'Gestionnaire'), ('CLIENT', 'Client')], default='CLIENT', max_length=15)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CM')),
                ('addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('type_piece_identite', models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('AUTRE', 'Autre')], max_length=20, null=True)),
                ('numero_piece_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='VALIDE', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_contrat_signe', models.FileField(blank=True, null=True, upload_to='contrats/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel')], default='MENSUEL', max_length=20)),
                ('bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats_directs', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='gestionBatiment.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='gestionBatiment.client')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='gestionBatiment.contrat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux', to='gestionBatiment.batiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bureau',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureaux', to='gestionBatiment.niveau'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='gestionBatiment.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='gestionBatiment.reservation'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureaux', to='gestionBatiment.typebureau'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('mois_paye', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True)),
                ('annee_paye', models.IntegerField(default=2026, null=True)),
                ('mode', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('TRANSFER', 'Virement bancaire')], default='CASH', max_length=20)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('PENDING_ADMIN', 'En attente administrateur'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestionBatiment.client')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestionBatiment.contrat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='gestionBatiment.location')),
            ],
            options={
                'unique_together': {('contrat', 'mois_paye', 'annee_paye')},
            },
        ),
        migrations.AddConstraint(
            model_name='bureau',
            constraint=models.UniqueConstraint(fields=('batiment', 'numero'), name='unique_numero_bureau_par_batiment'),
        ),
    ]
