# Generated by Django 6.0.5 on 2026-07-06 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestionBatiment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiement",
            name="date",
        ),
    ]
