# Generated by Django 6.0.5 on 2026-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRAVAILLEUR', 'Travailleur'), ('MANAGER', 'Gestionnaire'), ('CLIENT', 'Client')], default='CLIENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PENDING_ADMIN', 'En attente Admin'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
    ]
