# Generated by Django 6.0.5 on 2026-07-06 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0002_remove_paiement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
