# Generated by Django 6.0.5 on 2026-06-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0003_client_id_alter_client_role_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PENDING_ADMIN', 'En attente Administrateur'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
    ]
