# Generated by Django 4.2.11 on 2026-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0003_paiement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente de validation"),
                    ("VALIDEE", "Validée"),
                    ("REJETEE", "Rejetée"),
                ],
                default="VALIDEE",
                max_length=20,
            ),
        ),
    ]
