# Generated by Django 4.2.11 on 2026-07-20 07:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("gestionBatiment", "0004_reservation_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batiment",
            name="proprietaire_telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="BI"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="BI"
            ),
        ),
    ]
