# Generated by Django 6.0.5 on 2026-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0005_remove_client_id_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annee_paye',
            field=models.IntegerField(default=2026, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mois_paye',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(blank=True, help_text="Date d'encaissement", null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant versé pour ce mois', max_digits=14),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PENDING_ADMIN', 'En attente validation Admin'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('contrat', 'mois_paye', 'annee_paye')},
        ),
    ]
