# Generated by Django 4.2.11 on 2026-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0005_alter_batiment_proprietaire_telephone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="compte_bancaire",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="document_bancaire",
            field=models.ImageField(blank=True, null=True, upload_to="clients/recu/"),
        ),
    ]
