# Generated by Django 4.2.11 on 2026-08-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0006_paiement_compte_bancaire_paiement_document_bancaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="document_bancaire",
            field=models.FileField(blank=True, null=True, upload_to="clients/recu/"),
        ),
    ]
