# Generated by Django 6.0.5 on 2026-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0006_paiement_annee_paye_paiement_mois_paye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='annee_paye',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mois_paye',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True),
        ),
    ]
