# Generated by Django 6.0.5 on 2026-06-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0007_alter_paiement_annee_paye_alter_paiement_mois_paye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_facturation',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel')], default='MENSUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestionBatiment.contrat'),
        ),
        migrations.AddConstraint(
            model_name='bureau',
            constraint=models.UniqueConstraint(fields=('batiment', 'numero'), name='unique_numero_bureau_par_batiment'),
        ),
    ]
