# Generated by Django 6.0.5 on 2026-06-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0008_bureau_statut_contrat_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bureau',
            old_name='unite',
            new_name='prix_unite',
        ),
    ]
