# Generated by Django 6.0.5 on 2026-06-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0009_rename_unite_bureau_prix_unite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bureau',
            old_name='prix_unite',
            new_name='prix_unitaire',
        ),
    ]
