# Generated by Django 6.0.5 on 2026-06-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0011_remove_location_date_debut_remove_location_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='gestionBatiment.reservation'),
        ),
    ]
